server:
  port: 9011
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: BUS-SERVER
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/sc-bus